### ISSUE TITLE
Few URL updates in README

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/masonry#2]
PR: https://github.com/backdrop-contrib/masonry/pull/3

**Comment by laryn** [comment]
@BWPanda Just clicked that you are a maintainer on Drupal. Do you want to be a maintainer here as well?

**Comment by ghost** [comment]
@laryn Yeah, I actually wrote the Masonry modules originally years ago. But I haven't used them much anymore; so thanks for the offer, but no thanks :slightly_smiling_face:
